### ISSUE TITLE
Resurrect the project

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-java#130]
Clean up:

- [x] Move core APIs into `io.yarpc.core` (#131)
- [x] Split encodings into separate packages
    - [x] yarpc-encoding-raw (#132)
    - [x] yarpc-encoding-json (#135)
    - [x] yarpc-encoding-thrift (#133)
- [x] Move HTTP transport into the `yarpc-http` module (#137)
- [x] Delete TChannel transport (#138)
- [x] Drop Joda time: We require Java 8 so we can use `java.time` (#142)
- [x] Clean up dependencies: Now that every non-core functionality is a
      separate module, ensure that each module explicitly declares its
      dependencies
- [x] Move crossdock code outside yarpc-core
- [x] Fix coverage tracking (#139)

API updates

- [x] Exceptions: Delete ExceptionMessages class
- [x] Transport Request/Response
- [ ] ~~Context~~ (Tracking in #210)
- [x] Inbounds
- [x] Outbounds
- [x] Middleware

Testing and examples

- [ ] ~~Re-enable crossdock~~ (Tracking in #224)
- [ ] ~~Add examples~~ (Tracking in #226)

**Comment by abhinav** [comment]
Closing this issue in favor of the individual issues created for remaining tasks.
